//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books39_40.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id_Book { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Id_MaxDiscount { get; set; }
        public Nullable<int> Id_Maker { get; set; }
        public Nullable<int> Id_Category { get; set; }
        public Nullable<int> Id_Supplier { get; set; }
        public Nullable<int> Id_Ative_Discount { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ActiveDiscount ActiveDiscount { get; set; }
        public virtual Category Category { get; set; }
        public virtual Maker Maker { get; set; }
        public virtual MaxDiscount MaxDiscount { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
